version: "3.8"

services:
  avito-parser:
    build:
      context: "../"
      dockerfile: "./docker/dev.Dockerfile"
    restart: on-failure
    environment:
       - DB_URL
       - BOT_TOKEN
    volumes:
      - ../:/app
